# Generated by Django 5.2.3 on 2025-06-21 07:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="achievements/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("issue_date", models.DateField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="certifications/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("project_url", models.URLField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, help_text="Comma-separated tags", max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("conference", models.CharField(max_length=300)),
                ("publication_url", models.URLField()),
                ("published_date", models.DateField()),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "-published_date"],
            },
        ),
    ]
