# Generated by Django 5.2.3 on 2025-07-12 10:22

import uuid

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="achievements/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["display_order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("issue_date", models.DateField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="certifications/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["display_order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Daily Visitor Count",
                "verbose_name_plural": "Daily Visitor Counts",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("work_details", models.TextField(help_text="Detailed description of responsibilities and achievements")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professional Experience",
                "verbose_name_plural": "Professional Experiences",
                "ordering": ["display_order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(help_text="Full project details, including text, images, and code snippets."),
                ),
                ("image", models.ImageField(help_text="Main image for project preview/banner", upload_to="projects/banners/")),
                ("project_url", models.URLField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False, help_text="Select to show on homepage featured section")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("conference", models.CharField(max_length=300)),
                ("publication_url", models.URLField()),
                ("published_date", models.DateField()),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["display_order", "-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("pdf_file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TotalVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.UUID("1a2b3c4d-e5f6-7890-1234-567890abcdef"), editable=False, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Total Visitor Count",
                "verbose_name_plural": "Total Visitor Counts",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sender", models.CharField(choices=[("user", "User"), ("bot", "Bot")], max_length=4)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="api.chatsession")),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperiencePhoto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="experience/memories/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("experience", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="api.experience")),
            ],
            options={
                "verbose_name": "Experience Photo",
                "verbose_name_plural": "Experience Photos",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery_images", to="api.project")),
            ],
            options={
                "verbose_name": "Project Gallery Image",
                "verbose_name_plural": "Project Gallery Images",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="projects", to="api.tag"),
        ),
    ]
