# Generated by Django 5.2.3 on 2026-05-02 20:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("country", models.CharField(blank=True, db_index=True, default="Unknown", max_length=120)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop/Laptop"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("visited_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Visitor Analytics",
                "verbose_name_plural": "Visitor Analytics",
                "ordering": ["-visited_at"],
            },
        ),
    ]
