# Generated by Django 5.2.3 on 2025-06-23 19:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "work_details",
                    models.TextField(help_text="Detailed description of responsibilities and achievements"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professional Experience",
                "verbose_name_plural": "Professional Experiences",
                "ordering": ["display_order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("pdf_file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visitor Count",
                "verbose_name_plural": "Visitor Counts",
            },
        ),
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["display_order", "-date"],
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={
                "ordering": ["display_order", "-issue_date"],
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["display_order", "-published_date"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="code_snippet",
            field=models.TextField(blank=True, help_text="Code snippet for syntax highlighting", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Select to show on homepage featured section"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(help_text="Main image for project preview/banner", upload_to="projects/banners/"),
        ),
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.CreateModel(
            name="ExperiencePhoto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="experience/memories/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="api.experience"),
                ),
            ],
            options={
                "verbose_name": "Experience Photo",
                "verbose_name_plural": "Experience Photos",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Gallery Image",
                "verbose_name_plural": "Project Gallery Images",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="projects", to="api.tag"),
        ),
    ]
