# Generated by Django 5.2.3 on 2026-07-03 03:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_visitoranalytics"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCostTracking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation_type", models.CharField(choices=[("chat", "Chat"), ("embedding", "Embedding")], default="chat", max_length=20)),
                ("model_name", models.CharField(default="unknown", max_length=255)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ("total_chat_cost", models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ("total_embedding_cost", models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ("total_chat_tokens", models.PositiveIntegerField(default=0)),
                ("total_embedding_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for embedding costs, or linked for chat session costs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="api.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Cost Tracking",
                "verbose_name_plural": "LLM Cost Tracking",
                "ordering": ["-created_at"],
            },
        ),
    ]
