# Generated by Django 5.2.3 on 2025-07-12 04:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chatsession_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="code_snippet",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Full project details, including text, images, and code snippets."),
        ),
    ]
