# Generated by Django 5.2.3 on 2025-07-12 10:00

import uuid

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chatsession_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Daily Visitor Count",
                "verbose_name_plural": "Daily Visitor Counts",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TotalVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.UUID("1a2b3c4d-e5f6-7890-1234-567890abcdef"), editable=False, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Total Visitor Count",
                "verbose_name_plural": "Total Visitor Counts",
            },
        ),
        migrations.DeleteModel(
            name="VisitorCount",
        ),
        migrations.RemoveField(
            model_name="project",
            name="code_snippet",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Full project details, including text, images, and code snippets."),
        ),
    ]
