# Generated by Django 5.2.3 on 2026-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_llmcosttracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcosttracking",
            name="cost",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_chat_cost",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_cost",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_embedding_cost",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
