# Generated by Django 5.2.3 on 2026-07-04 03:44

import django.db.models.deletion
from django.db import migrations, models


def remove_duplicate_sessions(apps, schema_editor):
    LLMCostTracking = apps.get_model("api", "LLMCostTracking")
    from django.db.models import Count

    # Find duplicate session_ids, ignoring null sessions
    duplicates = LLMCostTracking.objects.values("session").annotate(session_count=Count("session")).filter(session_count__gt=1, session__isnull=False)

    for duplicate in duplicates:
        session_id = duplicate["session"]
        # Get all records for this session, ordered by newest first
        duplicate_records = LLMCostTracking.objects.filter(session_id=session_id).order_by("-created_at")
        # Keep the first (newest), delete the rest
        ids_to_delete = [record.id for record in list(duplicate_records)[1:]]
        LLMCostTracking.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_llmcosttracking_decimal_places"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_sessions, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="llmcosttracking",
            options={"ordering": ["-updated_at"], "verbose_name": "LLM Cost Tracking", "verbose_name_plural": "LLM Cost Tracking"},
        ),
        migrations.RemoveField(
            model_name="llmcosttracking",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="llmcosttracking",
            name="tokens_used",
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="job_name",
            field=models.CharField(blank=True, help_text="Identifier for background jobs like index_content", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_chat_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_chat_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_embedding_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_embedding_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="operation_type",
            field=models.CharField(choices=[("chat", "Chat Session"), ("embedding", "Embedding Job")], default="chat", max_length=50),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="session",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked for chat session costs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_tracking",
                to="api.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_chat_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_embedding_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
    ]
