# Generated by Django 5.2.3 on 2026-07-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_llmcosttracking_decimal_places"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmcosttracking",
            options={"ordering": ["-updated_at"], "verbose_name": "LLM Cost Tracking", "verbose_name_plural": "LLM Cost Tracking"},
        ),
        migrations.RemoveField(
            model_name="llmcosttracking",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="llmcosttracking",
            name="tokens_used",
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="job_name",
            field=models.CharField(blank=True, help_text="Identifier for background jobs like index_content", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_chat_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_chat_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_embedding_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_embedding_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="session_total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmcosttracking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="operation_type",
            field=models.CharField(choices=[("chat", "Chat Session"), ("embedding", "Embedding Job")], default="chat", max_length=50),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="session",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked for chat session costs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_tracking",
                to="api.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_chat_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="llmcosttracking",
            name="total_embedding_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
    ]
