# Generated by Django 5.2.3 on 2025-07-12 09:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_project_code_snippet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Daily Visitor Count",
                "verbose_name_plural": "Daily Visitor Counts",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TotalVisitorCount",
            fields=[
                ("id", models.UUIDField(default=uuid.UUID("1a2b3c4d-e5f6-7890-1234-567890abcdef"), editable=False, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Total Visitor Count",
                "verbose_name_plural": "Total Visitor Counts",
            },
        ),
        migrations.DeleteModel(
            name="VisitorCount",
        ),
    ]
