# Generated by Django 5.2.3 on 2026-08-27 03:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_llmcosttracking_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("visitor_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("page", models.CharField(max_length=500)),
                ("visited_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Page Visit",
                "verbose_name_plural": "Page Visits",
                "ordering": ["-visited_at"],
            },
        ),
        migrations.AddField(
            model_name="visitoranalytics",
            name="visitor_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
